In [1]:
import pandas as pd
import numpy as np

In [2]:
# fpath = "../../data/output/NEON-DOMAINS-HSE.csv"
fpath = "../../data/output/NEON-DOMAINS-HSE-2020to2023.csv"
hse_df = pd.read_csv(fpath)

In [3]:
print(hse_df.columns)

Index(['domain', 'alpha', 'beta', 'a', 'b', 'alpha_R2', 'alpha_rmse',
       'beta_R2', 'beta_rmse', 'HSE', 'k'],
      dtype='object')

In [4]:
hse_df

,domain,alpha,beta,a,b,alpha_R2,alpha_rmse,beta_R2,beta_rmse,HSE,k
0,D01,2.1572,0.6012,0.3861,2.4172,0.7948,0.6186,0.6737,0.2475,2.1698,0.1374
1,D02,2.2710,0.6878,0.3844,1.8789,0.8567,0.6814,0.8163,0.2526,1.6368,0.4157
2,D03,2.4100,0.5978,0.1554,1.9862,0.7237,1.0622,0.6068,0.3779,1.9355,0.6481
3,D04,3.4556,0.3366,0.0487,2.5282,0.5530,1.2323,0.3851,0.2721,3.4865,0.0829
4,D05,2.4488,0.6189,0.1375,2.3758,0.8349,0.6954,0.7739,0.2372,1.7829,0.4439
5,D06,2.8204,0.5321,0.1342,2.0938,0.8734,0.7112,0.6918,0.3004,1.9383,0.4634
6,D07,2.3704,0.6310,0.2226,2.2403,0.8375,0.7500,0.8015,0.2866,1.7990,0.3486
7,D08,2.6336,0.6360,0.1501,2.1019,0.8372,0.8452,0.7857,0.2568,1.5109,0.6445
8,D10,1.8393,0.5969,0.2969,1.6349,0.5313,0.8107,0.5970,0.2815,2.5111,0.6488
9,D11,2.9187,0.5095,0.1542,1.6502,0.8263,0.6523,0.6997,0.2490,2.0065,0.9081
10,D12,2.8231,0.5426,0.0492,1.9606,0.8793,0.7181,0.8643,0.2395,1.8628,1.7008
11,D13,2.2290,0.7632,0.1119,0.9100,0.7380,0.7827,0.6317,0.3532,1.3917,11.4434
12,D14,NaN,0.8936,NaN,0.5258,NaN,NaN,0.4397,0.2172,NaN,NaN
13,D15,2.3559,0.1550,0.7807,2.3267,0.4221,0.7376,0.0872,0.2551,11.5460,0.0000
14,D16,2.1004,0.8010,0.3335,1.3291,0.8866,0.6551,0.8748,0.2875,1.3965,1.4735
15,D17,2.2601,0.7142,0.2322,1.0253,0.7540,1.0605,0.8130,0.3402,1.5404,4.0151
16,D19,2.7256,0.6659,0.0487,1.4185,0.8095,0.7548,0.6888,0.2925,1.2777,7.1902
17,D20,2.7748,0.5558,0.0535,2.0948,0.7370,1.1261,0.7135,0.3204,1.8238,1.3068

In [5]:
## Creaete a new df and save
out_df = hse_df.copy()

In [6]:
alpha_list = []
beta_list = []
for i in range(len(out_df)):
    col_str = f"{out_df['alpha'].values[i].round(3).astype(str)} ({out_df['alpha_rmse'].values[i].round(2).astype(str)}, {out_df['alpha_R2'].values[i].round(2).astype(str)})"
    alpha_list.append(col_str)

    col_str = f"{out_df['beta'].values[i].round(3).astype(str)} ({out_df['beta_rmse'].values[i].round(2).astype(str)}, {out_df['beta_R2'].values[i].round(2).astype(str)})"
    beta_list.append(col_str)
    
out_df['alpha'] = alpha_list
out_df['beta'] = beta_list

In [7]:
out_df

,domain,alpha,beta,a,b,alpha_R2,alpha_rmse,beta_R2,beta_rmse,HSE,k
0,D01,"2.253 (0.62, 0.85)","0.668 (0.28, 0.85)",0.2941,1.9426,0.8507,0.6235,0.8511,0.2782,1.7394,0.4662
1,D02,"2.29 (0.68, 0.86)","0.678 (0.26, 0.91)",0.3637,1.9245,0.8637,0.6819,0.9117,0.2563,1.6605,0.3985
2,D03,"2.16 (1.11, 0.74)","0.694 (0.54, 0.65)",0.2718,1.4214,0.7379,1.1051,0.6534,0.5407,1.7197,1.3367
3,D04,"3.447 (1.24, 0.56)","0.353 (0.28, 0.51)",0.0488,2.4232,0.5582,1.2368,0.5106,0.2792,3.2176,0.1363
4,D05,"2.468 (0.7, 0.84)","0.633 (0.26, 0.85)",0.1302,2.2676,0.8379,0.7015,0.8523,0.2608,1.6902,0.5786
5,D06,"2.806 (0.72, 0.88)","0.571 (0.31, 0.78)",0.1382,1.8270,0.8751,0.7167,0.7824,0.3114,1.6987,0.8749
6,D07,"2.372 (0.75, 0.84)","0.661 (0.29, 0.86)",0.2218,2.0167,0.8424,0.7519,0.8638,0.2875,1.6532,0.5402
7,D08,"2.629 (0.84, 0.85)","0.648 (0.26, 0.88)",0.1524,2.0092,0.8465,0.8409,0.8781,0.2620,1.4565,0.7618
8,D09,"3.098 (0.12, 0.57)","0.068 (0.04, 0.37)",0.2093,2.0339,0.5748,0.1197,0.3748,0.0355,27.2876,0.0000
9,D10,"1.842 (0.81, 0.53)","0.637 (0.28, 0.74)",0.2951,1.4466,0.5332,0.8107,0.7382,0.2792,2.2985,1.0629
10,D11,"2.871 (0.66, 0.85)","0.504 (0.28, 0.8)",0.1665,1.6619,0.8479,0.6555,0.8002,0.2799,2.0995,0.7993
11,D12,"2.806 (0.72, 0.88)","0.54 (0.24, 0.88)",0.0509,1.9685,0.8805,0.7183,0.8839,0.2392,1.8946,1.6026
12,D13,"2.229 (0.77, 0.77)","0.737 (0.34, 0.73)",0.1107,0.9696,0.7682,0.7693,0.7332,0.3395,1.4859,9.8275
13,D14,"nan (nan, nan)","0.307 (0.18, 0.59)",NaN,2.0207,NaN,NaN,0.5934,0.1774,NaN,NaN
14,D15,"2.671 (0.8, 0.47)","0.213 (0.25, 0.24)",0.4856,1.9758,0.4674,0.7981,0.2408,0.2518,7.7124,0.0035
15,D16,"2.153 (0.68, 0.89)","0.726 (0.31, 0.88)",0.2881,1.6187,0.8899,0.6827,0.8753,0.3141,1.6000,0.9216
16,D17,"2.256 (1.04, 0.77)","0.688 (0.32, 0.85)",0.2354,1.0662,0.7653,1.0378,0.8462,0.3209,1.6495,3.5258
17,D19,"2.694 (0.75, 0.84)","0.664 (0.29, 0.78)",0.0513,1.3985,0.8359,0.7542,0.7813,0.2913,1.3201,7.0913
18,D20,"2.775 (1.13, 0.74)","0.559 (0.32, 0.76)",0.0535,2.0775,0.7370,1.1261,0.7569,0.3171,1.8029,1.3672

In [7]:
# outfp = "../../data/output/NEON-DOMAINS-HSE-TEXTFORTABLE.csv"
outfp = "../../data/output/NEON-DOMAINS-HSE-2020to2023-TEXTFORTABLE.csv"
out_df.to_csv(outfp)