In [1]:
import pandas as pd
import numpy as np

In [2]:
fpath = "../../data/output/NEON-DOMAINS-HSE.csv"
# fpath = "../../data/output/NEON-DOMAINS-HSE-2020to2023.csv"
hse_df = pd.read_csv(fpath)

In [3]:
print(hse_df.columns)

Index(['domain', 'alpha', 'beta', 'a', 'b', 'alpha_R2', 'alpha_rmse',
       'beta_R2', 'beta_rmse', 'HSE', 'k'],
      dtype='object')

In [4]:
hse_df

,domain,alpha,beta,a,b,alpha_R2,alpha_rmse,beta_R2,beta_rmse,HSE,k
0,D01,2.2529,0.6684,0.2941,1.9426,0.8507,0.6235,0.8511,0.2782,1.7394,0.4662
1,D02,2.2898,0.6779,0.3637,1.9245,0.8637,0.6819,0.9117,0.2563,1.6605,0.3985
2,D03,2.1601,0.6945,0.2718,1.4214,0.7379,1.1051,0.6534,0.5407,1.7197,1.3367
3,D04,3.4471,0.3531,0.0488,2.4232,0.5582,1.2368,0.5106,0.2792,3.2176,0.1363
4,D05,2.4682,0.6332,0.1302,2.2676,0.8379,0.7015,0.8523,0.2608,1.6902,0.5786
5,D06,2.8065,0.5706,0.1382,1.8270,0.8751,0.7167,0.7824,0.3114,1.6987,0.8749
6,D07,2.3715,0.6612,0.2218,2.0167,0.8424,0.7519,0.8638,0.2875,1.6532,0.5402
7,D08,2.6293,0.6481,0.1524,2.0092,0.8465,0.8409,0.8781,0.2620,1.4565,0.7618
8,D09,3.0978,0.0681,0.2093,2.0339,0.5748,0.1197,0.3748,0.0355,27.2876,0.0000
9,D10,1.8420,0.6368,0.2951,1.4466,0.5332,0.8107,0.7382,0.2792,2.2985,1.0629
10,D11,2.8714,0.5037,0.1665,1.6619,0.8479,0.6555,0.8002,0.2799,2.0995,0.7993
11,D12,2.8057,0.5405,0.0509,1.9685,0.8805,0.7183,0.8839,0.2392,1.8946,1.6026
12,D13,2.2293,0.7366,0.1107,0.9696,0.7682,0.7693,0.7332,0.3395,1.4859,9.8275
13,D14,NaN,0.3074,NaN,2.0207,NaN,NaN,0.5934,0.1774,NaN,NaN
14,D15,2.6712,0.2131,0.4856,1.9758,0.4674,0.7981,0.2408,0.2518,7.7124,0.0035
15,D16,2.1532,0.7264,0.2881,1.6187,0.8899,0.6827,0.8753,0.3141,1.6000,0.9216
16,D17,2.2558,0.6884,0.2354,1.0662,0.7653,1.0378,0.8462,0.3209,1.6495,3.5258
17,D19,2.6941,0.6635,0.0513,1.3985,0.8359,0.7542,0.7813,0.2913,1.3201,7.0913
18,D20,2.7748,0.5590,0.0535,2.0775,0.7370,1.1261,0.7569,0.3171,1.8029,1.3672

In [5]:
## Creaete a new df and save
out_df = hse_df.copy()

In [6]:
alpha_list = []
beta_list = []
for i in range(len(out_df)):
    col_str = f"{out_df['alpha'].values[i].round(3).astype(str)} ({out_df['alpha_rmse'].values[i].round(2).astype(str)}, {out_df['alpha_R2'].values[i].round(2).astype(str)})"
    alpha_list.append(col_str)

    col_str = f"{out_df['beta'].values[i].round(3).astype(str)} ({out_df['beta_rmse'].values[i].round(2).astype(str)}, {out_df['beta_R2'].values[i].round(2).astype(str)})"
    beta_list.append(col_str)
    
out_df['alpha'] = alpha_list
out_df['beta'] = beta_list

In [7]:
# outfp = "../../data/output/NEON-DOMAINS-HSE-TEXTFORTABLE.csv"
outfp = "../../data/output/NEON-DOMAINS-HSE-2020to2023-TEXTFORTABLE.csv"
out_df.to_csv(outfp)

In [ ]:
###########
###########
###########

In [21]:
# read in fia regression data
fia_results = pd.read_csv("../../data/raw/FIA_HEX_GEDI_BIOMASS_REGRESSIONS_HSE_NEONALLDATA.csv")

In [22]:
fia_results.drop(columns=["Unnamed: 0"],inplace=True)

In [23]:
# Get domain ids in proper format
domain_list = []
for i in range(len(fia_results)):
    domain_num_str = int(fia_results['domain'].values[i])
    if domain_num_str<10:
        domain_str = f"D0{domain_num_str}"
    else:
        domain_str = f"D{domain_num_str}"

    domain_list.append(domain_str)
    
fia_results['domain'] = domain_list

In [24]:
merged_df = pd.merge(hse_df, fia_results, on="domain")

In [25]:
merged_df

,domain,alpha,beta,a,b,alpha_R2,alpha_rmse,beta_R2,beta_rmse,HSE,k,slope,intercept,r2,rmse
0,D01,2.2529,0.6684,0.2941,1.9426,0.8507,0.6235,0.8511,0.2782,1.7394,0.4662,0.96,33.07,0.443,27.360
1,D02,2.2898,0.6779,0.3637,1.9245,0.8637,0.6819,0.9117,0.2563,1.6605,0.3985,0.97,30.56,0.298,23.283
2,D03,2.1601,0.6945,0.2718,1.4214,0.7379,1.1051,0.6534,0.5407,1.7197,1.3367,1.14,18.00,0.487,21.357
3,D04,3.4471,0.3531,0.0488,2.4232,0.5582,1.2368,0.5106,0.2792,3.2176,0.1363,2.39,4.49,0.260,16.873
4,D05,2.4682,0.6332,0.1302,2.2676,0.8379,0.7015,0.8523,0.2608,1.6902,0.5786,0.90,25.22,0.198,29.106
5,D06,2.8065,0.5706,0.1382,1.8270,0.8751,0.7167,0.7824,0.3114,1.6987,0.8749,0.82,4.53,0.544,11.016
6,D07,2.3715,0.6612,0.2218,2.0167,0.8424,0.7519,0.8638,0.2875,1.6532,0.5402,1.35,9.13,0.674,24.976
7,D08,2.6293,0.6481,0.1524,2.0092,0.8465,0.8409,0.8781,0.2620,1.4565,0.7618,2.19,14.49,0.542,20.882
8,D09,3.0978,0.0681,0.2093,2.0339,0.5748,0.1197,0.3748,0.0355,27.2876,0.0000,3.02,0.23,0.606,4.897
9,D10,1.8420,0.6368,0.2951,1.4466,0.5332,0.8107,0.7382,0.2792,2.2985,1.0629,0.39,0.66,0.048,2.220
10,D11,2.8714,0.5037,0.1665,1.6619,0.8479,0.6555,0.8002,0.2799,2.0995,0.7993,0.43,6.04,0.732,6.975
11,D12,2.8057,0.5405,0.0509,1.9685,0.8805,0.7183,0.8839,0.2392,1.8946,1.6026,1.04,16.13,0.751,22.198
12,D13,2.2293,0.7366,0.1107,0.9696,0.7682,0.7693,0.7332,0.3395,1.4859,9.8275,4.61,3.59,0.677,14.545
13,D14,NaN,0.3074,NaN,2.0207,NaN,NaN,0.5934,0.1774,NaN,NaN,1.77,-0.72,0.532,3.831
14,D15,2.6712,0.2131,0.4856,1.9758,0.4674,0.7981,0.2408,0.2518,7.7124,0.0035,3.59,5.04,0.608,17.796
15,D16,2.1532,0.7264,0.2881,1.6187,0.8899,0.6827,0.8753,0.3141,1.6000,0.9216,3.01,14.94,0.644,62.778
16,D17,2.2558,0.6884,0.2354,1.0662,0.7653,1.0378,0.8462,0.3209,1.6495,3.5258,2.52,5.05,0.665,43.052

In [27]:
merged_df.to_csv("../../data/output/NEON-HSE-ALLYEARS-WITHGEDIRESULTS.csv", index=False)